- src/utils/comparator/unorderComparator.js
- test/utils/unorderComparator.test.js
We know that entities are great values to understand the intention (match intents).
So the Unorder-Comparators take in count the weight of each token and use it to compute final score comparison. This method add a bigger matters to entities in sentences.
> Feature - Weighting UnorderComparator

- src/aice/index.js
- src/intentsResolver/intentResolver.js
- src/intentsResolver/intentResolverManager.js
- src/intentsResolver/simpleIntentResolver.js
- test/inputRevolver/inputResolverManager.test.js
> Feature topic

- README.md
- package.json
- src/aice/index.js
- src/intentsResolver/intentResolver.js
- src/intentsResolver/intentResolverManager.js
- src/intentsResolver/simpleIntentResolver.js
- test/inputRevolver/inputResolver.test.js
- test/inputRevolver/inputResolverManager.test.js
> Feature previous intents

- .circleci/config.yml
> fix deploy AIce in CircleCI

- packages/aice-cli/package.json
- packages/aice/package.json
- packages/aice/src/index.js
> feature packages : use hybrid approach #44

- CHANGELOG.md
- lerna.json
- package.json
- packages/aice-cli/CHANGELOG.md
- packages/aice-cli/bin/aice
- packages/aice-cli/bin/aice.js
- packages/aice-cli/package.json
- packages/aice-cli/src/cli.js
- packages/aice-cli/src/commands/validate.js
- packages/aice-nfm/CHANGELOG.md
- packages/aice-nfm/package.json
- packages/aice-utils/CHANGELOG.md
- packages/aice-utils/package.json
- packages/aice/CHANGELOG.md
- packages/aice/package.json
> fix: lerna publish package dist

- package.json
- packages/aice-cli/bin/aice.js
- packages/aice-utils/.babelrc
- packages/aice-utils/package.json
- yarn.lock
> fix: aice cmd tool starting

- packages/aice-utils/__tests__/aice-utils.test.js
- packages/aice-utils/src/index.js
> feat(aice-utils): done #56

- packages/aice-utils/__tests__/agentsManager.test.js
- packages/aice-utils/src/AgentsManager.js
- packages/aice-utils/src/index.js
- packages/aice-utils/src/models/Agent.js
> feat(aice-utils): create Agent and AgentsManager #54

- packages/aice/__tests__/fixes/index.test.js
- packages/aice/__tests__/outputRendering/simpleOutputRenderer.test.js
- packages/aice/src/intentResolvers/SimpleIntentResolver.js
- packages/aice/src/outputRendering/SimpleOutputRenderer.js
- packages/aice/src/utils/comparator/Comparator.js
- packages/aice/src/utils/comparator/wordsComparator/strategies.js
> fix(aice): exact match #63

- packages/aice-cli/bin/aice.js
- packages/aice-cli/src/cli.js
- packages/aice-cli/src/commands/Command.js
- packages/aice-cli/src/commands/run.js
- packages/aice-cli/src/commands/test.js
- packages/aice-cli/src/commands/validate.js
- packages/aice-cli/src/commands/version.js
- packages/aice-nfm/__tests__/fileManager.test.js
- packages/aice-nfm/src/FileManager.js
- packages/aice-utils/__tests__/agentsManager.test.js
- packages/aice-utils/__tests__/import/configurations.test.js
- packages/aice-utils/__tests__/import/opennlxv1.test.js
- packages/aice-utils/__tests__/import/opennlxv2.test.js
- packages/aice-utils/__tests__/import/testset.test.js
- packages/aice-utils/__tests__/testset/testset.test.js
- packages/aice-utils/__tests__/validate/configurations.test.js
- packages/aice-utils/src/AgentsManager.js
- packages/aice-utils/src/index.js
- packages/aice-utils/src/models/Agent.js
- packages/aice-utils/src/models/Configuration.js
> feat(aice-cli): test command

- packages/aice-cli/.eslintrc
- packages/aice-cli/bin/aice.js
- packages/aice-nfm/.eslintrc
- packages/aice-utils/.eslintrc
- packages/aice-utils/__tests__/agentsManager.test.js
- packages/aice-utils/__tests__/import/testset.test.js
- packages/aice/.eslintrc
> fix: error EsLint dynamic import

- packages/aice-cli/src/commands/test.js
- packages/aice-utils/__tests__/agentsManager.test.js
- packages/aice-utils/__tests__/aice-utils.test.js
- packages/aice-utils/src/AgentsManager.js
- packages/aice-utils/src/TestsManager.js
- packages/aice-utils/src/schemas/aice-testset/v1.json
> feat(aice-utils): tests compare contexts

- packages/aice-utils/__tests__/import/configurations.test.js
- packages/aice-utils/__tests__/import/errors.test.js
- packages/aice-utils/__tests__/import/opennlxv1.test.js
- packages/aice-utils/__tests__/import/opennlxv2.test.js
- packages/aice-utils/__tests__/import/testset.test.js
- packages/aice-utils/src/SchemaModelsManager.js
- packages/aice-utils/src/index.js
- packages/aice-utils/src/models/Configuration.js
- packages/aice-utils/src/models/OpennlxV1.js
- packages/aice-utils/src/models/OpennlxV2.js
- packages/aice-utils/src/models/SchemaModel.js
- packages/aice-utils/src/models/Testset.js
- packages/aice/__tests__/fixes/index.test.js
- packages/aice/__tests__/nlpaice.test.js
> feat(aice-utils): import merge content

- packages/aice/.eslintrc
- packages/aice/__tests__/fixes/index.test.js
- packages/aice/__tests__/inputRevolver/inputResolver.test.js
- packages/aice/__tests__/nlpaice.test.js
- packages/aice/__tests__/services.test.js
- packages/aice/__tests__/utils/utils.test.js
- packages/aice/src/AICE.js
- packages/aice/src/intentResolvers/IntentResolver.js
- packages/aice/src/intentResolvers/IntentResolverManager.js
- packages/aice/src/intentResolvers/SimpleIntentResolver.js
- packages/aice/src/issues.js
- packages/aice/src/outputRendering/OutputRenderer.js
- packages/aice/src/outputRendering/SimpleOutputRenderer.js
- packages/aice/src/services.js
- packages/aice/src/utils/Utils.js
> feat(aice): services

- packages/aice-cli/src/cli.js
- packages/aice-cli/src/commands/test.js
- packages/aice-nfm/__tests__/fileManager.test.js
- packages/aice-nfm/src/FileManager.js
- packages/aice-utils/__tests__/aice-utils.test.js
- packages/aice-utils/__tests__/import/errors.test.js
- packages/aice-utils/__tests__/import/testset.test.js
- packages/aice-utils/__tests__/testset/testset.test.js
- packages/aice-utils/__tests__/validate/errors.test.js
- packages/aice-utils/src/AgentsManager.js
- packages/aice-utils/src/TestsManager.js
- packages/aice-utils/src/index.js
- packages/aice-utils/src/models/Agent.js
- packages/aice-utils/src/models/Configuration.js
- packages/aice-utils/src/models/OpennlxV2.js
- packages/aice-utils/src/models/SchemaModel.js
- packages/aice-utils/src/models/Testset.js
- packages/aice-utils/src/schemas/aice-configuration/v1.json
- packages/aice/__tests__/fixes/index.test.js
- packages/aice/__tests__/outputRendering/simpleOutputRenderer.test.js
- packages/aice/src/AICE.js
- packages/aice/src/issues.js
- packages/aice/src/outputRendering/OutputRenderer.js
- packages/aice/src/outputRendering/SimpleOutputRenderer.js
> Feature [aice-cli] test command should display issues

- packages/aice-utils/__tests__/testset/testset.test.js
- packages/aice-utils/src/TestsManager.js
- packages/aice-utils/src/schemas/aice-testset/v1.json
> feature(aice-utils): add testset id, next, subStory properties

- packages/aice-cli/src/commands/test.js
> feat(aice-cli): test command add scenario and story option #72

- packages/aice-cli/bin/aice.js
- packages/aice-cli/package.json
- packages/aice-cli/src/cli.js
- packages/aice-utils/__tests__/agentsManager.test.js
- packages/aice-utils/__tests__/aice-utils.test.js
- packages/aice-utils/__tests__/callables/factory.test.js
- packages/aice-utils/__tests__/testset/testset.test.js
- packages/aice-utils/src/AgentsManager.js
- packages/aice-utils/src/CallableFactory.js
- packages/aice-utils/src/SchemaModelsManager.js
- packages/aice-utils/src/TestsManager.js
- packages/aice-utils/src/callables/AbstractCallable.js
- packages/aice-utils/src/callables/JsonWebservicesCallable.js
- packages/aice-utils/src/index.js
- packages/aice-utils/src/schemas/aice-testset/v1.json
- packages/aice/__tests__/tools.test.js
- packages/aice/src/AICE.js
- packages/aice/src/outputRendering/OutputRenderer.js
- packages/aice/src/outputRendering/SimpleOutputRenderer.js
> feat(aice-utils): implements callableFactory

- packages/aice-utils/__tests__/import/testset.test.js
- packages/aice-utils/src/models/Testset.js
> feat(aice-utils): testset merge stories inside scenarios

- packages/aice-utils/__tests__/agentsManager.test.js
- packages/aice-utils/src/AgentsManager.js
- packages/aice-utils/src/index.js
- packages/aice-utils/src/schemas/aice-configuration/v1.json
- packages/aice/__tests__/fixes/index.test.js
- packages/aice/__tests__/nlpaice.test.js
- packages/aice/__tests__/streamTransformers/ner.utteranceBased.test.js
- packages/aice/__tests__/streamTransformers/tokenizer.ner.test.js
- packages/aice/__tests__/utils/comparator.entities.test.js
- packages/aice/src/AICE.js
- packages/aice/src/intentResolvers/SimpleIntentResolver.js
- packages/aice/src/streamTransformers/expression/ExpressionParser.js
- packages/aice/src/streamTransformers/expression/InputExpressionTokenizer.js
- packages/aice/src/streamTransformers/expression/OutputExpressionTokenizer.js
- packages/aice/src/streamTransformers/models/DoubleLinkedList.js
- packages/aice/src/streamTransformers/ner/EnumEntity.js
- packages/aice/src/streamTransformers/ner/NERManager.js
- packages/aice/src/streamTransformers/tokenizer/AdvancedTokenizer.js
- packages/aice/src/streamTransformers/tokenizer/BasicTokenizer.js
- packages/aice/src/streamTransformers/tokenizer/NamedEntityTokenizer.js
- packages/aice/src/utils/comparator/Comparator.js
- packages/aice/src/utils/comparator/wordsComparator/levenshtein.js
- packages/aice/src/utils/openNLXSyntaxAdapter.js
Entities are not working as expected. If they are enabled, AICE.evaluate returns some wrong unmatched intents. But these intents are matching correctly when entities are disabled.
Issues:
Checklist:
> fix: entities are broken

- packages/aice-utils/src/TestsManager.js
> feat(aice-utils): compare trim message

- packages/aice-utils/__tests__/agentsManager.test.js
- packages/aice-utils/__tests__/testset/testset.test.js
- packages/aice-utils/src/TestsManager.js
- packages/aice-utils/src/schemas/aice-testset/v1.json
test(aice-utils): fix coverage
Issues:
Checklist:
> feat(aice-utils): story state

- packages/aice-utils/__tests__/testset/testset.test.js
- packages/aice-utils/src/TestsManager.js
- packages/aice-utils/src/models/Agent.js
- packages/aice-utils/src/schemas/aice-testset/v1.json
> feat(utils): add story.finalContext

- packages/aice-cli/package.commonjs.json
- packages/aice-cli/package.json
- packages/aice-nfm/package.commonjs.json
- packages/aice-nfm/package.json
- packages/aice-utils/__tests__/testset/testset.test.js
- packages/aice-utils/package.commonjs.json
- packages/aice-utils/package.json
- packages/aice/package.commonjs.json
- packages/aice/package.json
> add a package.json in commonjs modules
